version: 1
accounts:
- name: dcval1
  coins:
  - 4200000xbar
  - 4200000000edst
- name: dc1faucet
  coins:
  - 10000xbar
  - 100edst
- name: diana
  coins:
  - 100000xbar
  - 10000edst
faucet:
  name: dc1faucet
  coins:
  - 5xbar
  - 100edst
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: edst
        amount: '1500'
    distribution:
      params:
        community_tax: '0.010000000000000000'
        base_proposer_reward: '0.010000000000000000'
        bonus_proposer_reward: '0.050000000000000000'
    gov:
      params:
        expedited_min_deposit: 
          amount: '500'
          denom: edst
        min_deposit: 
          amount: '100'
          denom: edst
    mint:
      params:
        mint_denom: edst
    staking:
      params:
        bond_denom: edst
        max_validators: '47'
        unbonding_time: '1814400s'
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
validators:
- name: dcval1
  bonded: 1000000000edst
