version: 1
accounts:
- name: dcval1
  coins:
  - 4200000xbar
  - 4200000000000000uedst
- name: dc1faucet
  coins:
  - 10000xbar
  - 100000000uedst
- name: diana
  coins:
  - 100000xbar
  - 10000000uedst
faucet:
  name: dc1faucet
  coins:
  - 5xbar
  - 100000uedst
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: uedst
        amount: '1500000000'
    distribution:
      params:
        community_tax: '0.010000000000000000'
        base_proposer_reward: '0.010000000000000000'
        bonus_proposer_reward: '0.050000000000000000'
    gov:
      params:
        expedited_min_deposit: 
          amount: '500000000'
          denom: uedst
        min_deposit: 
          amount: '100000000'
          denom: uedst
    mint:
      params:
        mint_denom: uedst
    staking:
      params:
        bond_denom: uedst
        max_validators: '47'
        unbonding_time: '1814400s'
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
validators:
- name: dcval1
  bonded: 1000000000uedst
