version: 1
accounts:
- name: dcval1
  coins:
  - 4200000xbar
  - 4200000000000000uedst
- name: dc1faucet
  coins:
  - 10000xbar
  - 100000000uedst
- name: diana
  coins:
  - 100000xbar
  - 10000000uedst
faucet:
  name: dc1faucet
  coins:
  - 5xbar
  - 100000uedst
  port: 5555
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
validators:
- name: dcval1
  bonded: 1000000000uedst
