swagger: '2.0'
info:
  title: HTTP API Console dastchain.tokenfactory
  name: ''
  description: ''
paths:
  /dastchain/tokenfactory/denom:
    get:
      operationId: Query_DenomAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              denom:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    description:
                      type: string
                    ticker:
                      type: string
                    precision:
                      type: integer
                      format: int32
                    url:
                      type: string
                    maxSupply:
                      type: integer
                      format: int32
                    supply:
                      type: integer
                      format: int32
                    canChangeMaxSupply:
                      type: boolean
                    owner:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /dastchain/tokenfactory/denom/{denom}:
    get:
      operationId: Query_Denom
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              denom:
                type: object
                properties:
                  denom:
                    type: string
                  description:
                    type: string
                  ticker:
                    type: string
                  precision:
                    type: integer
                    format: int32
                  url:
                    type: string
                  maxSupply:
                    type: integer
                    format: int32
                  supply:
                    type: integer
                    format: int32
                  canChangeMaxSupply:
                    type: boolean
                  owner:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: denom
          in: path
          required: true
          type: string
      tags:
        - Query
  /dastchain/tokenfactory/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Denom:
    type: object
    properties:
      denom:
        type: string
      description:
        type: string
      ticker:
        type: string
      precision:
        type: integer
        format: int32
      url:
        type: string
      maxSupply:
        type: integer
        format: int32
      supply:
        type: integer
        format: int32
      canChangeMaxSupply:
        type: boolean
      owner:
        type: string
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  Params:
    type: object
  QueryAllDenomResponse:
    type: object
    properties:
      denom:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            description:
              type: string
            ticker:
              type: string
            precision:
              type: integer
              format: int32
            url:
              type: string
            maxSupply:
              type: integer
              format: int32
            supply:
              type: integer
              format: int32
            canChangeMaxSupply:
              type: boolean
            owner:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetDenomResponse:
    type: object
    properties:
      denom:
        type: object
        properties:
          denom:
            type: string
          description:
            type: string
          ticker:
            type: string
          precision:
            type: integer
            format: int32
          url:
            type: string
          maxSupply:
            type: integer
            format: int32
          supply:
            type: integer
            format: int32
          canChangeMaxSupply:
            type: boolean
          owner:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgCreateDenomResponse:
    type: object
  MsgUpdateDenomResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
